
package dwindle;

import java.util.Random;

/**
 *
 * @author YuTsai
 */
public class ConsumptionGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConsumptionGUI
     */
    public ConsumptionGUI() {
        initComponents();
        
        // display player stats
        resourceLabel.setText("Resources: " + Stats.resources);
        resourceDiceLabel.setText("Resource Dice: " + Stats.resourceDice);
        healthLabel.setText("Player Health: " + Stats.health);
        dayLabel.setText("Day: " + Stats.day);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        finishButton = new javax.swing.JButton();
        eatButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        resourceLabel = new javax.swing.JLabel();
        resourceDiceLabel = new javax.swing.JLabel();
        healthLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("How many resources are consumed?");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 212, 25));

        jLabel2.setText("For every resource under 4, a damage will be dealth");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, 288, 24));

        finishButton.setBackground(new java.awt.Color(255, 255, 255));
        finishButton.setForeground(new java.awt.Color(51, 0, 51));
        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(finishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 96, 32));

        eatButton.setBackground(new java.awt.Color(255, 255, 255));
        eatButton.setForeground(new java.awt.Color(51, 0, 51));
        eatButton.setText("Use Consumption Dice!");
        eatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eatButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(eatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, -1, -1));
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 315, 237, 23));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        resourceLabel.setForeground(new java.awt.Color(255, 255, 255));
        resourceLabel.setText("Resources: 5");

        resourceDiceLabel.setForeground(new java.awt.Color(255, 255, 255));
        resourceDiceLabel.setText("Resource Dice: 11");

        healthLabel.setForeground(new java.awt.Color(255, 255, 255));
        healthLabel.setText("Player Health: 10");

        dayLabel.setForeground(new java.awt.Color(255, 255, 255));
        dayLabel.setText("Day: 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resourceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(resourceDiceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(healthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(dayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resourceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resourceDiceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(healthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eatButtonActionPerformed

        Random rand = new Random();
        if(Stats.resourceDice > 0){
            Stats.resourceDice--;
            int incr = (int) (Math.random()*6+1);
            Stats.resources += incr;
            
            //update stats on GUI
            resourceLabel.setText("Resources: " + Stats.resources);
            resourceDiceLabel.setText("Resource Dice: " + Stats.resourceDice);
            jLabel4.setText("You have gained " + incr + " resources.");
        }
        else{
            jLabel4.setText("You do not have any more resource dice to spend.");
        }
    }//GEN-LAST:event_eatButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed

        ConsumptionGUI2 cgui2 = new ConsumptionGUI2();
        cgui2.setVisible(true);
        dispose();
    }//GEN-LAST:event_finishButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsumptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsumptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsumptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsumptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsumptionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayLabel;
    private javax.swing.JButton eatButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resourceDiceLabel;
    private javax.swing.JLabel resourceLabel;
    // End of variables declaration//GEN-END:variables
}
